name: Python application unittest

on:
  push:
    branches: main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests_mock
        pip install pytest
        pip install pytest-mock
        pip install responses
    - name: Run tests
      run: PYTHONPATH=. pytest tests
